# include all R packages in your project
library(devtools)
library(knitr)
library(rmarkdown)
library(xtable)
library(ggplot2)
sink("../../session-info.txt")
system("git --version")
system("latex --version")
system("pandoc --version")
cat("Session Information\n\n")
print(sessionInfo())
print(devtools::session_info(), "\n")
sink()

