# include all R packages in your project
library(devtools)
library(knitr)
library(rmarkdown)
library(xtable)
library(ggplot2)
sink("../../session-info.txt", append = TRUE)
cat("Session Information\n\n")
print(sessionInfo())
print(devtools::session_info())
print(system("git --version"))
print(system("latex --version"))
print(system("pandoc --version"))
sink()

